version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
